### ISSUE TITLE
Abbreviation Detector chunker

### ISSUE THREAD

**Issue by danielhoadley** [nationalarchives/ds-caselaw-data-enrichment-service#1]
The abbreviation detector currently breaks the incoming judgment into five chunks, which is sufficient for the vast majority of judgments. For longer judgments (or for very long ones, like _ACL Netherlands_) the number of chunks needs to be increased to prevent a memory error.

**Comment by amyconroy** [comment]
@imanehaf yes agree, should update it to reflect the size of the judgment
