### ISSUE TITLE
Ontology review

### ISSUE THREAD

**Issue by dragon-dxw** [nationalarchives/ds-caselaw-data-enrichment-service#57]
Two major questions that I think we've discussed at length and I don't think should be a surprise:

* We had discussed that ontology URLs containing hashes were going to not be used -- what would be used in their place?

* We had discussed that ontology URLs would be namespaced with `http://caselaw.nationalarchives.gov.uk/def` -- is that going to be the case?

And a few minor things that I saw whilst giving the ontology some close attention

* We have `caselaw:AdministrativeCourt` but `caselaw:Administrative_Appeals_Chamber` with different casing -- also `CommercialCourt`, `GeneralCourt`. 

* `appealedTo` evokes feelings of referring to a court, but targets a judgment. (This might be overly nitpicky, and might be reasonable language. Not sure if `appealedIn` is better.)

* `JudgmentExpression` appears to be completely disconnected from the graph, presumably connected by the FRBR ontology; is that correct?

**Comment by danielhoadley** [comment]
> Two major questions that I think we've discussed at length and I don't think should be a surprise: 
> * We had discussed that ontology URLs containing hashes were going to not be used -- what would be used in their place?
> * We had discussed that ontology URLs would be namespaced with http://caselaw.nationalarchives.gov.uk/def -- is that going to be the case?


These points were resolved in https://github.com/nationalarchives/ds-caselaw-data-enrichment-service/pull/58

**Comment by danielhoadley** [comment]
> We have caselaw:AdministrativeCourt but caselaw:Administrative_Appeals_Chamber with different casing -- also CommercialCourt, GeneralCourt.

This issue was resolved in https://github.com/nationalarchives/ds-caselaw-data-enrichment-service/pull/124
